### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by vv-monsalve**
@ibo-o This PR updates the requirements to solve the build.

### CODE REVIEW

**Review by ibo-o — APPROVED** [review]

**Comment by ibo-o** [comment]
Unfortunately the fail remains still.
Apparently there is something missing called `Ninja`
https://github.com/Element-Type/HostGrotesk/actions/runs/10936696773/job/30361351635#step:7:211

**Comment by vv-monsalve** [comment]
Screenshot 2024-09-19 at 13 01 45

<br><br>
The CI-run from my past PR was stopped by you in this repo, and [was working](https://github.com/vv-monsalve/HostGrotesk/actions/runs/10857833806) on my branch at PR time.

This new PR updates the requirements to fix the issue, and it's working on my end, both locally and in the fix [branch](https://github.com/vv-monsalve/HostGrotesk/actions/runs/10931002861). So I'm not sure what is happening here.

@simoncozens, could you please provide advice?

**Comment by simoncozens** [comment]
I'm not sure what's different except for the cache, so I would try clearing that first. (Repo owner should follow instructions at https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#deleting-cache-entries)

If that doesn't work, next step is to look at the two logs line by line and see what's different... The problem is something to do with installing pycairo, which the run is trying to build from source. (Side note: I wonder why it doesn't install a binary wheel?)

**Comment by ibo-o** [comment]
It seems that deleting the cache solved the problem. I didn't know that cancelling runs may cause issues. Thanks for your help

**Comment by vv-monsalve** [comment]
Thank you, Simon!

@ibo-o I'm Glad to hear it's working now. Canceling runs is not problematic in itself, but it makes it impossible to verify whether the CI is working.

**Pull request merged**
